### ISSUE TITLE
Why not delete old eggs?

### ISSUE THREAD

**Issue by Trii** [Goldmund-Wyldebeast-Wunderliebe/buildout.eggscleaner#6]
This is a pretty cool extension and about half of what I was looking for. Why not have it delete old eggs or at least have an option to enable that behavior? If you're interested, I'll add it and make a pull request.

**Comment by puittenbroek** [comment]
It currently has the option to move eggs to a new directory via the old-eggs-directory.
Removing them from that directory I leave to the user ;) Main reason for this is that it's 99% accurate. Certain eggs/recipe are somehow not included and get moved/reported, when they shouldn't..  supervisor related stuff for one.

But feel free to make a PR for your feature, but keep the 99% accuracy in mind ;)

**Comment by Kilte** [comment]
I could to add an option for this.

**Comment by puittenbroek** [comment]
That sounds good @Kilte
