### ISSUE TITLE
Don't move eggs, when an error has occurred

### ISSUE THREAD

**Issue by Kilte** [Goldmund-Wyldebeast-Wunderliebe/buildout.eggscleaner#8]
While:
  Installing.
  Getting section sphinxbuilder.
  Initializing section sphinxbuilder.
  Getting option sphinxbuilder:eggs.
  Getting section package.
Error: The referenced section, 'package', was not defined.
*************** BUILDOUT EGGSCLEANER ****************
Moved unused egg: ....
Moved unused egg: ....
Moved unused egg: ....
Moved unused egg: ....
*************** /BUILDOUT EGGSCLEANER ****************

**Comment by Kilte** [comment]
There is a pull request, which fixes this error: #9

**Comment by puittenbroek** [comment]
Thanks @Kilte for the PR! Merged it, hope to make a new release next week.

**Comment by puittenbroek** [comment]
@Kilte Could you also make a PR to update the doc?

**Comment by Kilte** [comment]
@puittenbroek as i understand, this question relates to #10 PR. Yes, I can, but a little later.

**Comment by puittenbroek** [comment]
Yeah, docs for #10 explaning the new option

**Comment by Kilte** [comment]
#9
